### ISSUE TITLE
Dependency: openapi

### ISSUE THREAD

**Issue by sneumann** [lifs-tools/rmzTab-m#6]
Hi, docs and `DESCRIPTION` need information about `library(openapi)`:
https://github.com/lifs-tools/rmzTab-m/blob/30d5208d45bdb8f5c48773b8c79480badcec2159/R/validate_api.R#L65

I couldn't locate that package :-(
Yours, Steffen

**Comment by nilshoffmann** [comment]
Closing, issue is fixed in PR #7
